var data = 
[
	{"source":{"name" : "WarmMagnetInterlock 8" , "id" : "WARM_MAGNET_INTERLOCK7" , "type" : "WarmMagnetInterlock"},"target":{"name" : "BeamLossMonitorCrate 2" , "id" : "BEAM_LOSS_MONITOR_CRATE1" , "type" : "BeamLossMonitorCrate"},"type":"suit"}, 
	{"source":{"name" : "PoweringInterlock 6" , "id" : "POWERING_INTERLOCK5" , "type" : "PoweringInterlock"},"target":{"name" : "PoweringInterlock 1" , "id" : "POWERING_INTERLOCK0" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "SafeMachineParameter 3" , "id" : "SAFE_MACHINE_PARAMATER2" , "type" : "SafeMachineParameter"},"target":{"name" : "BeamLossMonitorCrate 2" , "id" : "BEAM_LOSS_MONITOR_CRATE1" , "type" : "BeamLossMonitorCrate"},"type":"suit"}, 
	{"source":{"name" : "BeamLossMonitorCrate 2" , "id" : "BEAM_LOSS_MONITOR_CRATE1" , "type" : "BeamLossMonitorCrate"},"target":{"name" : "WarmMagnetInterlock 8" , "id" : "WARM_MAGNET_INTERLOCK7" , "type" : "WarmMagnetInterlock"},"type":"suit"}, 
	{"source":{"name" : "SafeMachineParameter 5" , "id" : "SAFE_MACHINE_PARAMATER4" , "type" : "SafeMachineParameter"},"target":{"name" : "PoweringInterlock 7" , "id" : "POWERING_INTERLOCK6" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "WarmMagnetInterlock 10" , "id" : "WARM_MAGNET_INTERLOCK9" , "type" : "WarmMagnetInterlock"},"target":{"name" : "PoweringInterlock 6" , "id" : "POWERING_INTERLOCK5" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "WarmMagnetInterlock 8" , "id" : "WARM_MAGNET_INTERLOCK7" , "type" : "WarmMagnetInterlock"},"target":{"name" : "WarmMagnetInterlock 10" , "id" : "WARM_MAGNET_INTERLOCK9" , "type" : "WarmMagnetInterlock"},"type":"suit"}, 
	{"source":{"name" : "PoweringInterlock 6" , "id" : "POWERING_INTERLOCK5" , "type" : "PoweringInterlock"},"target":{"name" : "WarmMagnetInterlock 4" , "id" : "WARM_MAGNET_INTERLOCK3" , "type" : "WarmMagnetInterlock"},"type":"suit"}, 
	{"source":{"name" : "PoweringInterlock 7" , "id" : "POWERING_INTERLOCK6" , "type" : "PoweringInterlock"},"target":{"name" : "WarmMagnetInterlock 4" , "id" : "WARM_MAGNET_INTERLOCK3" , "type" : "WarmMagnetInterlock"},"type":"suit"}, 
	{"source":{"name" : "BeamLossMonitorCrate 9" , "id" : "BEAM_LOSS_MONITOR_CRATE8" , "type" : "BeamLossMonitorCrate"},"target":{"name" : "PoweringInterlock 1" , "id" : "POWERING_INTERLOCK0" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "WarmMagnetInterlock 10" , "id" : "WARM_MAGNET_INTERLOCK9" , "type" : "WarmMagnetInterlock"},"target":{"name" : "WarmMagnetInterlock 4" , "id" : "WARM_MAGNET_INTERLOCK3" , "type" : "WarmMagnetInterlock"},"type":"suit"}, 
	{"source":{"name" : "PoweringInterlock 7" , "id" : "POWERING_INTERLOCK6" , "type" : "PoweringInterlock"},"target":{"name" : "PoweringInterlock 6" , "id" : "POWERING_INTERLOCK5" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "PoweringInterlock 7" , "id" : "POWERING_INTERLOCK6" , "type" : "PoweringInterlock"},"target":{"name" : "WarmMagnetInterlock 8" , "id" : "WARM_MAGNET_INTERLOCK7" , "type" : "WarmMagnetInterlock"},"type":"suit"}, 
	{"source":{"name" : "SafeMachineParameter 3" , "id" : "SAFE_MACHINE_PARAMATER2" , "type" : "SafeMachineParameter"},"target":{"name" : "PoweringInterlock 7" , "id" : "POWERING_INTERLOCK6" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "PoweringInterlock 1" , "id" : "POWERING_INTERLOCK0" , "type" : "PoweringInterlock"},"target":{"name" : "WarmMagnetInterlock 4" , "id" : "WARM_MAGNET_INTERLOCK3" , "type" : "WarmMagnetInterlock"},"type":"suit"}, 
	{"source":{"name" : "BeamLossMonitorCrate 2" , "id" : "BEAM_LOSS_MONITOR_CRATE1" , "type" : "BeamLossMonitorCrate"},"target":{"name" : "SafeMachineParameter 5" , "id" : "SAFE_MACHINE_PARAMATER4" , "type" : "SafeMachineParameter"},"type":"suit"}, 
	{"source":{"name" : "WarmMagnetInterlock 8" , "id" : "WARM_MAGNET_INTERLOCK7" , "type" : "WarmMagnetInterlock"},"target":{"name" : "PoweringInterlock 7" , "id" : "POWERING_INTERLOCK6" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "SafeMachineParameter 5" , "id" : "SAFE_MACHINE_PARAMATER4" , "type" : "SafeMachineParameter"},"target":{"name" : "BeamLossMonitorCrate 9" , "id" : "BEAM_LOSS_MONITOR_CRATE8" , "type" : "BeamLossMonitorCrate"},"type":"suit"}, 
	{"source":{"name" : "WarmMagnetInterlock 8" , "id" : "WARM_MAGNET_INTERLOCK7" , "type" : "WarmMagnetInterlock"},"target":{"name" : "PoweringInterlock 1" , "id" : "POWERING_INTERLOCK0" , "type" : "PoweringInterlock"},"type":"suit"}, 
	{"source":{"name" : "PoweringInterlock 1" , "id" : "POWERING_INTERLOCK0" , "type" : "PoweringInterlock"},"target":{"name" : "BeamLossMonitorCrate 9" , "id" : "BEAM_LOSS_MONITOR_CRATE8" , "type" : "BeamLossMonitorCrate"},"type":"suit"}
	]